#!/bin/sh
for i in $@
do
    _BASENAME=$i
    _FILENAME=${_BASENAME%.*}
    _EXTENSION=${_BASENAME##*.}
    _NOW=`gdate '+%Y%m%d%H%M'`
    if test $_FILENAME != $_EXTENSION; then
        _COPYFILE=$_FILENAME-$_NOW.$_EXTENSION
        cp $_FILENAME{,-$_NOW}.$_EXTENSION
    else
        _COPYFILE=$_FILENAME-$_NOW
        cp $_FILENAME{,-$_NOW}
    fi
    echo -n $_COPYFILE
done
