#!/bin/sh
for i in $@
do
    _BASENAME=$i
    _FILENAME=${_BASENAME%.*}
    _EXTENSION=${_BASENAME##*.}
    if test $_FILENAME != $_EXTENSION; then
        _COPYFILE=$_FILENAME{,-`gdate '+%Y%m%d%H%M'`}.$_EXTENSION
    else
        $_COPYFILE=$_FILENAME{,-`gdate '+%Y%m%d%H%M'`}
    fi
    cp $_COPYFILE
    echo $_COPYFILE
done
